[자라나라] 테이블 작성
wecode-bootcamp-korea/27-1st-ZARANARA-backend pull request #1
Opened 2021-11-30 13:19 UTC by MinhyukK0

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [x] 리팩토링
- [x] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- erd를 바탕으로 앱 생성 및 모델 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 앱 생성 - 유저, 제품, 재고관리, 주문 

2. 각 앱의 models.py 작성

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 리뷰 내용 중 오더에 대한 내용을 추가 반영함으로써 추가 기능에 대한 확장성을 고려하게 됨.  
- 모델 작성 중 발생한 에러를 바탕으로 디버깅하며 import할 경우에 클래스명은 따옴표를 사용하지 않는다는 것을 알게됨
- 컨벤션 기준에 따라 수정함으로써 가독성 좋은 코드 작성할 수 있었음

<br />

## :: 기타 질문 및 특이 사항
-

2021-11-30 15:07 UTC, jamessoun93 requested changes
리뷰 남겨드렸으니 확인해주세요! 👍

2021-11-30 15:07 UTC, jamessoun93 commented on users/models.py
> +    email    = models.CharField(max_length=300, unique = True)
`=` 앞뒤 간격은 전체적으로 통일해주세요.
```suggestion
    email    = models.CharField(max_length=300, unique=True)
```

2021-11-30 15:07 UTC, jamessoun93 commented on users/models.py
> +    phone    = models.CharField(max_length=100, null = True)
`=` 앞뒤 간격은 전체적으로 통일해주세요.
```suggestion
    phone    = models.CharField(max_length=100, null=True)
```

2021-11-30 15:07 UTC, jamessoun93 commented on users/models.py
> +    zipcode = models.CharField(max_length=300, null = True)
```suggestion
    name    = models.CharField(max_length=300, null=True)
    zipcode = models.CharField(max_length=300, null=True)
```

2021-11-30 15:07 UTC, jamessoun93 commented on users/models.py
> +    name    = models.CharField(max_length=300, null = True)
address 테이블에서 name 이 어떤 정보를 담는 컬럼인지 불명확합니다.
어떤 정보를 담기위한 컬럼일까요?

2021-11-30 15:07 UTC, jamessoun93 commented on stocks/models.py
> +    product  = models.ForeignKey(Product, on_delete=models.CASCADE)
모델링 리뷰때 가이드 드린대로 잘 작성해주셨네요.
- 하지만 이 테이블은 꼭 재고관리만을 위한 테이블이 아닌 존재하는 product + options 의 조합을 담기위한 테이블입니다. 따라서 테이블명을 Stock 으로 지어주기보다는 ProductOptions 같은 테이블명이 낫지 않을까요?
- 재고는 quantity 보다는 stock 이라는 단어가 더 어울립니다.
- 여기서 제품의 가격을 관리하는게 좋은 아이디어인지는 잘 모르겠습니다. 상품 컬러, 사이즈별로 가격이 다르다면 이렇게 진행해도 되겠지만, Product 리스트 를 보내줘야하는 기능을 작성할때 가격을 가져오기 위해 항상 이 테이블을 경유해야하는 불편함이 있을 수 있겠네요. 가격 정보는 Product 테이블에서 관리하는게 더 좋아보이네요.

2021-11-30 15:07 UTC, jamessoun93 commented on products/models.py
> +class Product(TimeStampModel):
`thumbnail_image_url` 을 여기에 생성하기로 하지 않았었나요?!

2021-11-30 15:07 UTC, jamessoun93 commented on products/models.py
> +class Image(models.Model):
이렇게만 보면 상품이미지인지 우리 서비스에서 사용하는 모든 `image` 들을 담으려고하는지 구분이 가지 않습니다.
`product_images` 라는 테이블명이 더 명확하겠네요!

2021-11-30 15:07 UTC, jamessoun93 commented on products/models.py
> +class ThemePruduct(models.Model):
오타 확인해주세요!
```suggestion
class ThemeProduct(models.Model): 
```

2021-11-30 15:07 UTC, jamessoun93 commented on orders/models.py
> +        db_table = 'orders'
order_number 는 따로 생성해주지 않고 그냥 해당 테이블의 PK 를 활용하실 계획이신가요?

2021-11-30 15:07 UTC, jamessoun93 commented on orders/models.py
> +    delivery_status = models.ForeignKey('DeliveryStatus', on_delete=models.CASCADE)
여기는 특정 order 에 포함되어있는 제품들을 관리하는 테이블이죠? 특정 order 에 담겨있는 제품마다 tracking_number 와 delivery_status 가 따로 부여되는거라면 쿠팡처럼 한번에 담아도 낱개로 따로따로 배송되는 형태의 기획으로 생각하신걸까요?

2021-12-01 02:16 UTC, Daco2020 commented on users/models.py
> +    email    = models.CharField(max_length=300, unique = True)
일괄 수정 했습니다.

2021-12-01 02:16 UTC, Daco2020 commented on users/models.py
> +    phone    = models.CharField(max_length=100, null = True)
수정 했습니다.

2021-12-01 02:16 UTC, Daco2020 commented on users/models.py
> +    zipcode = models.CharField(max_length=300, null = True)
수정했습니다.

2021-12-01 02:17 UTC, Daco2020 commented on users/models.py
> +    name    = models.CharField(max_length=300, null = True)
name -> receiver 로 더 명확하게 수정하였습니다.
추가로 address라는 컬럼값을 추가하였습니다.

2021-12-01 02:19 UTC, Daco2020 commented on stocks/models.py
> +    product  = models.ForeignKey(Product, on_delete=models.CASCADE)
stock -> product options 로 수정하였습니다. 
quantity -> stock으로 컬럼명 수정하였습니다.
가격은 product 테이블로 이동하였습니다.
기존 stock 앱 모델내용을 product앱 모델로 이동하였습니다. (기존 스톡 앱은 사용하지 않아 제거하였습니다)

2021-12-01 02:21 UTC, Daco2020 commented on products/models.py
> +class Product(TimeStampModel):
옵션별로 썸네일을 사용하기 위해 product 테이블이 아닌 product option 테이블에 컬럼을 추가하였습니다. 만약 프론트와 상의 하여 추가이미지가 생긴다면 테이블 분리 예정입니다.

2021-12-01 02:21 UTC, Daco2020 commented on products/models.py
> +class Image(models.Model):
테이블명 수정하였습니다

2021-12-01 02:21 UTC, Daco2020 commented on products/models.py
> +class ThemePruduct(models.Model):
오타 수정하였습니다.

2021-12-01 02:21 UTC, Daco2020 commented on orders/models.py
> +        db_table = 'orders'
네 pk로 사용할 예정입니다.

2021-12-01 02:22 UTC, Daco2020 commented on orders/models.py
> +    delivery_status = models.ForeignKey('DeliveryStatus', on_delete=models.CASCADE)
낱개로 배송할 예정입니다.
예를들어 가구와 의류를 구매할 경우 각기 배송이 달라질 수 있기 때문입니다.

2021-12-01 02:23 UTC, Daco2020 commented
리뷰 감사합니다. 모두 수정 반영완료하여 push까지 완료하였습니다!

2021-12-01 03:10 UTC, lordmyshepherd commented
LGTM 👍🏻

2021-12-01 03:10 UTC, merged