[CREATED] 세트상품 상세이미지 _ SetProductView
wecode-bootcamp-korea/27-1st-ZARANARA-backend pull request #13
Opened 2021-12-07 09:57 UTC by Daco2020

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [x] 리팩토링
- [x] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 세트상품의 상세페이지 뷰 제작

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 세트상품의 상세페이지를 클라이언트에게 제공합니다.
- 상품정보를 반환합니다.
- 하위 상품의 정보를 반환합니다.
- 좋아요 여부를 확인할 수 있습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 불필요한 변수 할당을 줄이고 코드의 가독성을 줄이는 방법을 알게 되었습니다.
- 데코레이터를 활용하여 좋아요 여부를 확인하는 기능을 만들 수 있게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항

2021-12-07 11:00 UTC, Daco2020 commented
메인 머지 후 추가 커밋하였습니다.

2021-12-08 01:06 UTC, Daco2020 commented
like toggle 기능 추가하여 올렸습니다.

2021-12-08 01:38 UTC, lordmyshepherd requested changes

2021-12-08 01:38 UTC, lordmyshepherd commented on products/views.py
> +            return JsonResponse({'massage':"DoesNotExist"}, status=401)
LikeToggleView는 뭔가요? 설명해주실 수 있을까요?
추가로 PR 분리해주세요. 하나의 PR에 하나의 기능만 있도록 수정 부탁드립니다~

2021-12-08 01:54 UTC, Daco2020 commented
라이크토글기능은 좋아요 하트 아이콘을 누르면 좋아요가 되고 다시 누르면 해제되는 기능입니다. 
해당 기능 PR에서 제거하였습니다.

2021-12-08 01:54 UTC, Daco2020 commented on products/views.py
> +            return JsonResponse({'massage':"DoesNotExist"}, status=401)
라이크토글기능은 좋아요 하트 아이콘을 누르면 좋아요가 되고 다시 누르면 해제되는 기능입니다.
해당 기능 PR에서 제거하였습니다.

2021-12-08 04:06 UTC, Daco2020 commented
라이크토글 기능 제거하였는데 스테이터스가 수정요청으로 변경되어 다시 리뷰요청으로 변경하였습니다.

2021-12-08 06:47 UTC, merged