[CREATED] products앱 상세 페이지 detailview 작성
wecode-bootcamp-korea/27-1st-ZARANARA-backend pull request #5
Opened 2021-12-03 13:30 UTC by Daco2020

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [x] 리팩토링
- [x] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상세페이지에서 필요로 하는 데이터를 반환하는 'detailview' 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 패스파라미터로 넘어온 해당 상품의 정보들을 모두 불러온다.
- 사이즈, 컬러, 이미지는 1대다 관계이므로 모두 역참조하여 불러온다.
- 연관상품(테마로 묶인)에 대한 이름, 가격, 이미지들(슬라이드 구현을 위해 여러장이 필요함)을 모두 불러온다.
![image](https://user-images.githubusercontent.com/76890895/144696794-c0857638-7d4c-4da3-963f-ba6172c8bb96.png)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 패스파라미터를 활용해 데이터를 불러오는 방법을 알게되었습니다.
- 해당 상품의 정보뿐만 아니라 역참조, 정참조를 통해 데이터를 자유자재로 불러올 수 있음을 알게되었습니다.
- 연관상품의 경우 중간 테이블에서 테마를 찾아내 다시 해당되는 상품들을 정참조로 불러올 수 있음을 알게 되었습니다.
- 컴프리핸션을 사용하여 코드의 가독성을 높일 수 있음을 알게되었습니다.
- 프론트 상세페이지 담당자와 소통하며 데이터를 어떻게 가져오는게 좋을지 같이 의견을 나눔으로써 협업과 소통의 기쁨을 알게되었습니다.

<br />

## :: 기타 질문 및 특이 사항
- 현재 detailview에서 생겨날수 있는 에러에는 어떤 것들이 있을 지 궁금합니다. 현재는 상품에 대한 데이터가 없을 때 오류를 반환하도록 하였는데, 추가적으로 우려되는 에러들이 있을까요?

2021-12-05 07:13 UTC, Daco2020 commented
![image](https://user-images.githubusercontent.com/76890895/144737349-44a7daaf-c1d2-4747-908f-41b50ee7219c.png)
프론트의 요청에 따라 데이터 반환 형태를 수정하였습니다.

![image](https://user-images.githubusercontent.com/76890895/144737368-4d271936-29f9-43a5-98c3-aec6ee6c4954.png)
로그인한 유저가 좋아요를 누른 상품인지 여부를 확인할 수 있도록 불린값을 반환하도록 수정하였습니다.

2021-12-05 15:03 UTC, bigfanoftim requested changes

2021-12-05 15:03 UTC, bigfanoftim commented on db_uploder.py
> +import os, django, csv
csv 관련 파일 gitignore에 추가해주세요.

2021-12-05 15:03 UTC, bigfanoftim commented on products/views.py
> +            product_category    = product_data.category.name
추가적인 변수 지정이 굳이 없어도 충분히 가독성이 좋을 것 같습니다.
```suggestion
```

2021-12-05 15:03 UTC, bigfanoftim commented on products/views.py
> +            product_data           = Product.objects.get(id=product_id)
product가 좀 더 올바른 변수명이라고 생각됩니다.
```suggestion
            product                = Product.objects.get(id=product_id)
```

2021-12-05 15:05 UTC, bigfanoftim commented on products/views.py
> +            like_bool              = Like.objects.filter(user=1).exists() #임시로 유저아이디 1번을 지정하였음. 추후 토큰 데코레이터 추가 예정
로그인 데코레이터를 통해 boolean값을 반환하는 것은 좋은 생각입니다. 그러면 비로그인 유저의 상세페이지 로직은 어떻게 하면 좋을지 생각해주세요~

2021-12-05 15:09 UTC, bigfanoftim requested changes

2021-12-05 15:09 UTC, bigfanoftim commented on products/views.py
> +class DetailView(View):
보다 명확한 네이밍이 필요해보입니다!
```suggestion
class ProductDetailView(View):
```

2021-12-06 11:35 UTC, Daco2020 commented on db_uploder.py
> +import os, django, csv
추가하였습니다~!

2021-12-06 11:35 UTC, Daco2020 commented on products/views.py
> +            product_category    = product_data.category.name
삭제 하였습니다~!

2021-12-06 11:35 UTC, Daco2020 commented on products/views.py
> +            product_data           = Product.objects.get(id=product_id)
변경하였습니다~!

2021-12-06 11:36 UTC, Daco2020 commented on products/views.py
> +            like_bool              = Like.objects.filter(user=1).exists() #임시로 유저아이디 1번을 지정하였음. 추후 토큰 데코레이터 추가 예정
signincheckdecorator 를 추가하여 토큰이 확인되는 경우 like여부를 확인 할 수 있게 하였고 토큰이 없으면 false로 반환되도록 하였습니다. 비회원인 경우에는 like를 누를 수 없도록 프론트 단에서 막을 예정입니다~!

2021-12-06 11:36 UTC, Daco2020 commented on products/views.py
> +class DetailView(View):
네이밍 변경하였습니다~!

2021-12-07 02:16 UTC, bigfanoftim requested changes

2021-12-07 02:16 UTC, bigfanoftim commented on core/utils.py
> +                return func(self, request, *args, **kwargs)
0 보다는 None이 좀 더 명확해 보입니다.
```suggestion
            token        = request.headers.get('Authorization')

            if not token:
                request.user = None
                return func(self, request, *args, **kwargs)
```

2021-12-07 02:16 UTC, bigfanoftim commented on core/utils.py
> +    return wrapper
토큰에 문제가 있어서 나오는 에러인데  그대로 에러메세지 리턴없이 통과시켜주나요?

2021-12-07 02:16 UTC, bigfanoftim commented on core/utils.py
> +            request.user = user
굳이 여러번에 걸쳐서 변수 지정할 필요는 없어 보입니다.
```suggestion
            request.user = User.objects.get(id = payload['user_id'])
```

2021-12-07 02:16 UTC, bigfanoftim commented on products/views.py
> +            like_bool          = Like.objects.filter(user=request.user).exists()
위와 같이 데코레이터를 수정해준다면 에러핸들링과 동시에 의도했던 기능을 구현할 수 있을 것 같습니다.

2021-12-07 02:37 UTC, Daco2020 commented on core/utils.py
> +                return func(self, request, *args, **kwargs)
할당 값을 None으로 수정하였고 테스트도 완료하였습니다.

2021-12-07 02:38 UTC, Daco2020 commented on core/utils.py
> +    return wrapper
로그인 여부와 상관없이 페이지를 보여줘야한다고 생각했는데 에러는 에러로 핸들링 하는게 더 나은 걸까요?

2021-12-07 02:38 UTC, Daco2020 commented on core/utils.py
> +            request.user = user
수정완료하였습니다!

2021-12-07 02:39 UTC, Daco2020 commented on products/views.py
> +            like_bool          = Like.objects.filter(user=request.user).exists()
상세한 피드백 감사합니다~! 수정완료하여 다시 push하였습니다!

2021-12-07 07:07 UTC, Daco2020 commented
라이브 코드리뷰 때 받은 피드백 반영하여 push하였습니다.

2021-12-07 08:22 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2021-12-07 08:22 UTC, lordmyshepherd commented on core/utils.py
> +def SigninCheckDecorator(func):
데코레이터는 snake_case로 작성해 주세요~ 위에 SigninDecorator 데코레이터도 마찬가지 입니다~

2021-12-07 08:22 UTC, merged