[리뷰 반영]ProductMainView -> ProductSlideView, ProductSetView(예정)로 분할
wecode-bootcamp-korea/27-1st-ZARANARA-backend pull request #8
Opened 2021-12-06 07:06 UTC by MinhyukK0

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [x] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 페이지 단위로 구현 하였던 view를 기능별로 분할하였습니다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. ProductMainView -> ProductSlideView, ProductSetView(예정)
- products.views.py의 ProductMainView삭제
- products.views.py에서 ProductSlideView 생성

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 페이지단위로 view를 작성하면 하나의 기능에 문제가 생기면 전체 로직을 수정해야하기 때문에 기능별로 구현해놓는 것이 좋다는 것을 배웠습니다.

<br />

## :: 기타 질문 및 특이 사항
- 없습니다.

2021-12-06 09:50 UTC, bigfanoftim requested changes

2021-12-06 09:50 UTC, bigfanoftim commented on products/views.py
> +        slide_item = [{'slide_id':item.product.id,'slide_image' : item.product.productimage_set.all()[0].url, 'alt' : item.product.productimage_set.all()[0].alt} for item in items]
항상 가독성을 신경써주세요!
```suggestion
        slide_item = [{
            'slide_id'    : item.product.id,
            'slide_image' : item.product.productimage_set.all()[0].url, 
            'alt'         : item.product.productimage_set.all()[0].alt
        } for item in items ]
```

2021-12-06 10:06 UTC, MinhyukK0 commented on products/views.py
> +        slide_item = [{'slide_id':item.product.id,'slide_image' : item.product.productimage_set.all()[0].url, 'alt' : item.product.productimage_set.all()[0].alt} for item in items]
가독성 신경써서 수정했습니다!

2021-12-06 10:45 UTC, lordmyshepherd requested changes

2021-12-06 10:45 UTC, lordmyshepherd commented on products/views.py
> +class ProductSlideView(View):
Endpoint를 만드실 때, 페이지를 기준으로 만들면 안되고 데이터 기준으로 만들어 주셔야 합니다.
Slide에서 보여주는 상품이 아니라 상품 자체를 반환해주는 의미로 ProductListView로 만들어야 하는 것이죠.

2021-12-06 10:45 UTC, lordmyshepherd commented on products/views.py
> +        items      = ThemeProduct.objects.select_related('product','theme').filter(theme = Theme.objects.get(id =3))[offset:limit]
`Theme(id=3)` id 3인 theme이 무엇인지 코드를 작성한 사람만이 알 수 있습니다.
문제가 있겠죠?

2021-12-06 11:24 UTC, MinhyukK0 commented on products/views.py
> +        items      = ThemeProduct.objects.select_related('product','theme').filter(theme = Theme.objects.get(id =3))[offset:limit]
수정 했습니다!

2021-12-06 11:25 UTC, MinhyukK0 commented on products/views.py
> +class ProductSlideView(View):
ProductListView라는 기능을 따로 작성하여 사용할 예정이어서 ProductThemeView로  정정하였습니다.

2021-12-07 06:29 UTC, bigfanoftim requested changes

2021-12-07 06:29 UTC, bigfanoftim commented on products/views.py
> +        slide_item = []
아래에서 list-comprehension을 사용하셔서 이 부분은 생략해도 될 것 같습니다.
```suggestion
```

2021-12-07 06:36 UTC, lordmyshepherd commented
해당 PR은 닫아주세요~

2021-12-07 06:46 UTC, closed without merging